import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PUB_DIR = ROOT / 'publications'
ENTRIES_DIR = PUB_DIR / 'entries'
ENTRIES_DIR.mkdir(parents=True, exist_ok=True)

entries = [
    {
        'id': 'patent-2019-slow-detection-artifact-removal',
        'category': 'Patents and Technology Disclosures',
        'year': 2019,
        'type': 'Technology Disclosure',
        'title': 'Automated machine learning-based slow detection and classification system, and artifact removal in EEG',
        'authors': 'J. Dauwels, W. Y. Peh, J. Thomas, M. Birnbaum',
        'status': 'Technology disclosure accepted',
        'venue': 'NTUitive',
        'notes': 'Ref. ID: 2019-369-01-SGPRV',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'patent disclosure 2019 EEG automated slow detection artifact removal'
    },
    {
        'id': 'patent-2023-detection-slowing-patterns',
        'category': 'Patents and Technology Disclosures',
        'year': 2023,
        'type': 'Patent',
        'title': 'Detection of slowing patterns in EEG data',
        'authors': 'J. Dauwels, W. Y. Peh, J. Thomas, M. Birnbaum',
        'status': 'Patent pending',
        'venue': 'US20230104030A1 / WO2021183048A1',
        'notes': 'Patent application pending',
        'url': 'https://patents.google.com/patent/US20230104030A1/en',
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'patent pending EEG slowing patterns 2023'
    },
    {
        'id': 'patent-2019-epilepsy-diagnostic-system',
        'category': 'Patents and Technology Disclosures',
        'year': 2019,
        'type': 'Technology Disclosure',
        'title': 'Automated deep learning-based epilepsy diagnostic system',
        'authors': 'J. Dauwels, J. Thomas, P. Thangavel',
        'status': 'Technology disclosure accepted',
        'venue': 'NTUitive',
        'notes': 'Ref. ID: 2018-292-01-SG-PRV',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'patent disclosure 2019 epilepsy diagnostic system deep learning'
    },
    {
        'id': 'journal-2024-quantifying-epileptic-networks',
        'category': 'Lead Author Journal Publications',
        'year': 2024,
        'type': 'Journal Article',
        'title': 'Quantifying epileptic networks: every data point brings us a step closer to an optimized surgery',
        'authors': 'J. Thomas, K. Jaber, B. Frauscher',
        'status': 'Published',
        'venue': 'Brain Communications',
        'notes': 'vol. 6, no. 5, 2024, fcae349',
        'url': 'https://doi.org/10.1093/braincomms/fcae349',
        'doi': '10.1093/braincomms/fcae349',
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2024 Brain Communications epilepsy surgery networks'
    },
    {
        'id': 'journal-2024-seizure-matching-system',
        'category': 'Lead Author Journal Publications',
        'year': 2024,
        'type': 'Journal Article',
        'title': 'Development of a stereo-EEG based seizure matching system for clinical decision making in epilepsy surgery',
        'authors': 'J. Thomas, C. Abdallah, K. Jaber, M. Khweileh, O. Aron, I. Dolezalova, V. Gnatkovsky, D. Mansilla, P. Nevalainen, R. Pana, S. Schuele, J. Singh, A. Suller-Marti, A. Urban, J. Hall, F. Dubeau, L. Maillard, P. Kahane, J. Gotman, B. Frauscher',
        'status': 'Published',
        'venue': 'Journal of Neural Engineering',
        'notes': 'vol. 21, no. 5, 2024, 056025',
        'url': 'https://doi.org/10.1088/1741-2552/ad7323',
        'doi': '10.1088/1741-2552/ad7323',
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2024 seizure matching stereo-EEG clinical decision epilepsy surgery'
    },
    {
        'id': 'journal-2024-clinical-opinions-seizure-surgery',
        'category': 'Lead Author Journal Publications',
        'year': 2024,
        'type': 'Journal Article',
        'title': 'Investigating current clinical opinions in stereoelectroencephalography-informed epilepsy surgery',
        'authors': 'J. Thomas, C. Abdallah, Z. Cai, K. Jaber, J. Gotman, S. Beniczky, B. Frauscher',
        'status': 'Published',
        'venue': 'Epilepsia',
        'notes': 'vol. 65, no. 9, pp. 2662-2672, 2024',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2024 Epilepsia clinical opinions stereoelectroencephalography'
    },
    {
        'id': 'journal-2023-spikes-predict-surgery',
        'category': 'Lead Author Journal Publications',
        'year': 2023,
        'type': 'Journal Article',
        'title': 'A subpopulation of spikes predicts successful epilepsy surgery outcome',
        'authors': 'J. Thomas, P. Kahane, C. Abdallah, T. Avigdor, W. J. E. M. Zweiphenning, S. Chabardes, K. Jaber, V. Latreille, L. Minotti, J. Hall, F. Dubeau, J. Gotman, B. Frauscher',
        'status': 'Published',
        'venue': 'Annals of Neurology',
        'notes': 'vol. 93, no. 3, pp. 522–535, 2023',
        'url': 'https://onlinelibrary.wiley.com/doi/full/10.1002/ana.26548',
        'doi': '10.1002/ana.26548',
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2023 Annals of Neurology epilepsy surgery spikes outcome'
    },
    {
        'id': 'journal-2022-improving-automated-diagnosis',
        'category': 'Lead Author Journal Publications',
        'year': 2022,
        'type': 'Journal Article',
        'title': 'Improving automated diagnosis of epilepsy from EEGs beyond IEDs',
        'authors': 'P. Thangavel, J. Thomas, N. Sinha, W. Y. Peh, R. Yuvaraj, S. S. Cash, R. Chaudhari, S. Karia, R. Rathakrishnan, V. Saini, N. Shah, R. Srivastava, Y. L. Tan, B. Westover, J. Dauwels',
        'status': 'Published',
        'venue': 'Journal of Neural Engineering',
        'notes': 'vol. 19, no. 6, p. 066017, 2022',
        'url': 'https://doi.org/10.1088/1741-2552/ac9c93',
        'doi': '10.1088/1741-2552/ac9c93',
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2022 EEG epilepsy diagnosis automated diagnosis beyond IEDs'
    },
    {
        'id': 'journal-2021-automated-adult-epilepsy-diagnostic-tool',
        'category': 'Lead Author Journal Publications',
        'year': 2021,
        'type': 'Journal Article',
        'title': 'Automated adult epilepsy diagnostic tool based on interictal scalp electroencephalogram characteristics: A six-center study',
        'authors': 'J. Thomas, P. Thangavel, W. Y. Peh, J. Jin, R. Yuvaraj, S. Cash, R. Chaudhari, S. Karia, R. Rathakrishnan, N. Shah, R. Srivastava, Y. L. Tan, B. Westover, J. Dauwels',
        'status': 'Published',
        'venue': 'International Journal of Neural Systems',
        'notes': 'vol. 31, no. 05, p. 2050074, 2021',
        'url': 'https://doi.org/10.1142/S0129065720500744',
        'doi': '10.1142/S0129065720500744',
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2021 International Journal of Neural Systems epilepsy diagnostic tool interictal EEG'
    },
    {
        'id': 'journal-2020-automated-detection-ied',
        'category': 'Lead Author Journal Publications',
        'year': 2020,
        'type': 'Journal Article',
        'title': 'Automated detection of interictal epileptiform discharges from scalp electroencephalograms by convolutional neural networks',
        'authors': 'J. Thomas, J. Jin, P. Thangavel, E. Bagheri, R. Yuvaraj, J. Dauwels, R. Rathakrishnan, J. J. Halford, S. S. Cash, B. Westover',
        'status': 'Published',
        'venue': 'International Journal of Neural Systems',
        'notes': 'vol. 30, no. 11, p. 2050030, 2020',
        'url': 'https://doi.org/10.1142/S0129065720500306',
        'doi': '10.1142/S0129065720500306',
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2020 IED detection scalp EEG CNN'
    },
    {
        'id': 'review-2026-hierarchical-integration-multimodal-clinical-data',
        'category': 'Publications under review',
        'year': 2026,
        'type': 'Manuscript',
        'title': 'Hierarchical Integration of Multimodal Clinical Data to Predict Epilepsy Surgery Outcome',
        'authors': 'J. Thomas, C. Abdallah, T. Aung, P. B. Varela, I. Doležalová, P. Parikh, L. Wadi, K. Jaber, Z. Cai, A. Ho, M. K. Moye, E. Minato, O. Aron, S. Chabardes, S. Colnat-Coulbois, J. Hall, P. Klimes, L. Minotti, F. Dubeau, D. Southwell, D. Carlson, M. Brazdil, J. Gonzalez-Martinez, P. Kahane, L. Maillard, J. Gotman, B. Frauscher',
        'status': 'Under Review',
        'venue': 'In review',
        'notes': '',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'under review 2026 multimodal clinical data epilepsy surgery outcome'
    },
    {
        'id': 'review-2026-ai-applications-in-intracranial-eeg',
        'category': 'Publications under review',
        'year': 2026,
        'type': 'Manuscript',
        'title': 'Artificial Intelligence Applications in Intracranial Electroencephalography: Insights from AI Epilepsy 2025',
        'authors': 'B. Frauscher, M. F. Afzal, K. A. Davis, N. Provenza, S. Sheth, R. Smith, J. Thomas',
        'status': 'Under Review',
        'venue': 'In review',
        'notes': '',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'under review 2026 intracranial EEG artificial intelligence'
    },
    {
        'id': 'review-2026-time-frequency-representation-ee',
        'category': 'Publications under review',
        'year': 2026,
        'type': 'Manuscript',
        'title': 'A Comparative Study of Time-Frequency Representation Techniques for EEG Seizure Onset Detection using Deep Learning Models',
        'authors': 'N. Alshawa, R. Gabriel, J. Thomas, R. Yuvaraj, J. F. A. Ronickom',
        'status': 'Under Review',
        'venue': 'In review',
        'notes': '',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'under review 2026 EEG seizure onset detection time-frequency representation'
    },
    {
        'id': 'review-2026-thalamic-interictal-events',
        'category': 'Publications under review',
        'year': 2026,
        'type': 'Manuscript',
        'title': 'Thalamic Interictal Epileptic and Non-Epileptic Events during NREM Sleep in Patients with Focal Epilepsy: a Stereo-EEG Study',
        'authors': 'H. Ye, K. Jaber, A. Ho, L. Ye, J. Thomas, X. Xu, C. Chen, Y. Chen, G. Ren, M. Moye, T. Avigdor, P. Klimes, P. Parikh, D. Southwell, Z. Zheng, J. Zhu, S. Wang, B. Frauscher',
        'status': 'Under Review',
        'venue': 'In review',
        'notes': '',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'under review 2026 thalamic interictal events NREM stereo-EEG'
    },
    {
        'id': 'review-2026-preictal-period-quantification',
        'category': 'Publications under review',
        'year': 2026,
        'type': 'Manuscript',
        'title': 'Data-Driven Quantification of the Preictal Period in Epilepsy Using Scalp EEG: A Causal Observational Study',
        'authors': 'A. A. S. Gadda, A. Chahar, R. Yuvaraj, J. Thomas, J. F. A. Ronickom',
        'status': 'Under Review',
        'venue': 'In review',
        'notes': '',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'under review 2026 preictal period scalp EEG causal observational study'
    },
    {
        'id': 'review-2026-multi-paradigm-fusion-biometric-authentication',
        'category': 'Publications under review',
        'year': 2026,
        'type': 'Manuscript',
        'title': 'Multi-Paradigm Fusion for Task-Independent EEG-based Biometric Authentication',
        'authors': 'C. Rakshe, C. B. Thomas, M. Kalathe, V. S. Sreeraj, G. Venkatasubramanian, J. Thomas, R. Yuvaraj, D. Kumar, J. F. A. Ronickom',
        'status': 'Under Review',
        'venue': 'In review',
        'notes': '',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'under review 2026 EEG biometric authentication multi-paradigm fusion'
    },
    {
        'id': 'review-2026-sleep-fragmentation-epileptic-activity',
        'category': 'Publications under review',
        'year': 2026,
        'type': 'Manuscript',
        'title': 'Sleep fragmentation drives local, network-specific epileptic activity in human epilepsy',
        'authors': 'B. Frauscher, A. Ho, B. Matoušková, K. Jaber, T. Avigdor, E. Minato, J. Thomas, D. Southwell, J. Hall, P. Klimeš, L. Peter-Derex, S. Hannan',
        'status': 'Under Review',
        'venue': 'In review',
        'notes': '',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'under review 2026 sleep fragmentation epileptic activity network-specific'
    },
    {
        'id': 'review-2026-thalamo-temporal-connectivity-signatures',
        'category': 'Publications under review',
        'year': 2026,
        'type': 'Manuscript',
        'title': 'Thalamo-Temporal Structural and Functional Connectivity Signatures in relation to Surgical Outcome in Drug-Resistant Temporal Lobe Epilepsy',
        'authors': 'T. Tipakorn, L. Tang, C. Belly, J. Barrios-Martinez, J. Thomas, F. C. Yeh, J. G. Martinez, T. Aung',
        'status': 'Under Review',
        'venue': 'In review',
        'notes': '',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'under review 2026 thalamo-temporal connectivity surgical outcome'
    },
    {
        'id': 'review-2026-gamma-activity-criterion',
        'category': 'Publications under review',
        'year': 2026,
        'type': 'Manuscript',
        'title': 'Gamma activity: the seventh criterion for epileptiform discharges?',
        'authors': 'T. Avigdor, U. Fennig, J. Thomas, M. A. Kural, L. Duez, V. S. Hansen, P. G. Larsson, S. Rampp, R. Schulz, H. Tankisi, R. Wennberg, B. Frauscher, S. Beniczky',
        'status': 'Under Review',
        'venue': 'In review',
        'notes': '',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'under review 2026 gamma activity epileptiform discharges criterion'
    },
    {
        'id': 'review-2026-emotional-drift-pattern-visualization',
        'category': 'Publications under review',
        'year': 2026,
        'type': 'Manuscript',
        'title': 'EEG-Based Pattern Visualization of Emotional Drift During Short-Form Video Consumption',
        'authors': 'P. Yadav, R. Yuvaraj, C. Rakshe, J. Thomas, P. A. Karthick, J. F. A. Ronickom',
        'status': 'Under Review',
        'venue': 'In review',
        'notes': '',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'under review 2026 EEG emotional drift video consumption visualization'
    },
    {
        'id': 'review-2026-spectral-trajectory-sleep',
        'category': 'Publications under review',
        'year': 2026,
        'type': 'Manuscript',
        'title': 'Comparative Spectral Trajectory Analysis of Sleep Onset and Awakening Transitions Using Combined Polysomnography EEG',
        'authors': 'S. Prachi, P. A. Karthick, R. Yuvaraj, J. Thomas, J. F. A. Ronickom',
        'status': 'Under Review',
        'venue': 'In review',
        'notes': '',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'under review 2026 spectral trajectory sleep onset awakening transitions'
    },
    {
        'id': 'review-2026-spatial-characterization-40hz-assr',
        'category': 'Publications under review',
        'year': 2026,
        'type': 'Manuscript',
        'title': 'Spatial Characterization of 40 Hz Auditory Steady-State Evoked Potentials Using EEG',
        'authors': 'A. Chaudhary, J. Thomas, C. T. Rakshe, R. Yuvaraj, H. Shim, J. F. A. Ronickom',
        'status': 'Under Review',
        'venue': 'In review',
        'notes': '',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'under review 2026 40 Hz auditory steady-state evoked potentials EEG'
    },
    {
        'id': 'review-2026-feature-normalization-biometric-authentication',
        'category': 'Publications under review',
        'year': 2026,
        'type': 'Manuscript',
        'title': 'Impact of Feature Normalization on EEG-Based Biometric Authentication',
        'authors': 'C. T. Rakshe, C. B. Thomas, M. Kalathe, J. Thomas, R. Yuvaraj, J. F. A. Ronickom',
        'status': 'Under Review',
        'venue': 'In review',
        'notes': '',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'under review 2026 feature normalization biometric authentication EEG'
    },
    {
        'id': 'review-2026-ocular-semiology-framework',
        'category': 'Publications under review',
        'year': 2026,
        'type': 'Manuscript',
        'title': 'A Quantitative Ocular Semiology Framework for Epilepsy Surgery Decision-Making',
        'authors': 'M. Li, A. Thandar, J. Thomas',
        'status': 'Under Review',
        'venue': 'In review',
        'notes': '',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'under review 2026 ocular semiology epilepsy surgery decision-making'
    },
    {
        'id': 'journal-2026-thalamo-cortical-synchrony-seizure-expression',
        'category': 'Other Journal Publications',
        'year': 2026,
        'type': 'Journal Article',
        'title': 'Thalamo-cortical Synchrony Shapes Seizure Expression in Human Temporal Lobe Epilepsy',
        'authors': 'T. Aung, J. Li, T. Tumnark, C. Belly, J. Thomas, K. Jaber, P. Parikh, M. Zafar, D. Southwell, P. Chauvel, B. Frauscher, J. Gonzalez-Martinez',
        'status': 'In Press',
        'venue': 'Nature Communications',
        'notes': 'in press, 2026',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2026 in press Nature Communications thalamo-cortical synchrony seizure expression'
    },
    {
        'id': 'journal-2026-antiseizure-medication-taper',
        'category': 'Other Journal Publications',
        'year': 2026,
        'type': 'Journal Article',
        'title': 'Impact of Antiseizure Medication Taper on Electroencephalographic Dynamics in Focal Epilepsy: A Stereoelectroencephalographic Study',
        'authors': 'G. Ren, S. Hannan, K. Schiller, J. Thomas, M. Moye, T. Avigdor, K. Jaber, X. Wei, H. Ye, A. Ho, N. J. Ghosn',
        'status': 'Published',
        'venue': 'Epilepsia',
        'notes': '2026',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2026 Epilepsia antiseizure medication taper EEG dynamics'
    },
    {
        'id': 'journal-2026-maximizing-surgical-success-in-epilepsy',
        'category': 'Other Journal Publications',
        'year': 2026,
        'type': 'Journal Article',
        'title': 'Maximizing surgical success in epilepsy: seizure-onset zone resection is crucial, while extending beyond offers no added benefit',
        'authors': 'C. Abdallah, J. Thomas, O. Aron, T. Avigdor, K. Jaber, I. Doležalová, D. Mansilla, P. Nevalainen, P. Parikh, J. Singh, S. Beniczky',
        'status': 'In Press',
        'venue': 'Neurology',
        'notes': 'in press, 2026',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2026 in press Neurology surgical success seizure-onset zone resection'
    },
    {
        'id': 'journal-2025-response-to-comment-pulsatile-corticoid-therapy',
        'category': 'Other Journal Publications',
        'year': 2025,
        'type': 'Journal Article',
        'title': 'Response to the comment on: Reduction of interictal epileptic burden by pulsatile corticoid therapy in children with drug-resistant epilepsy—How stable is the effect?',
        'authors': 'K. Schiller, T. Avigdor, J. Thomas, D. Mansilla, C. Abdallah, A. Kortas, G. Unterholzner, R. Pana, M. Rauchenzauner, B. Frauscher',
        'status': 'Published',
        'venue': 'Epileptic Disorders',
        'notes': '2025',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2025 Epileptic Disorders response comment corticoid therapy'
    },
    {
        'id': 'journal-2025-reduction-interictal-epileptic-burden',
        'category': 'Other Journal Publications',
        'year': 2025,
        'type': 'Journal Article',
        'title': 'Reduction of interictal epileptic burden by pulsatile corticoid therapy in children with drug-resistant epilepsy—How stable is the effect?',
        'authors': 'K. Schiller, T. Avigdor, J. Thomas, D. Mansilla, C. Abdallah, A. Kortas, G. Unterholzner, R. Pana, M. Rauchenzauner, B. Frauscher',
        'status': 'Published',
        'venue': 'Epileptic Disorders',
        'notes': '2025',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2025 Epileptic Disorders pulsatile corticoid therapy'
    },
    {
        'id': 'journal-2025-visual-features-stereo-eeg',
        'category': 'Other Journal Publications',
        'year': 2025,
        'type': 'Journal Article',
        'title': 'Visual Features in Stereo‐Electroencephalography to Predict Surgical Outcome: A Multicenter Study',
        'authors': 'C. Abdallah, J. Thomas, O. Aron, T. Avigdor, K. Jaber, I. Doležalová, D. Mansilla, P. Nevalainen, P. Parikh, J. Singh, S. Beniczky',
        'status': 'Published',
        'venue': 'Annals of Neurology',
        'notes': '2025',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2025 Annals of Neurology visual features stereo-EEG surgical outcome'
    },
    {
        'id': 'journal-2025-widespread-decoupling-spindles-slow-waves',
        'category': 'Other Journal Publications',
        'year': 2025,
        'type': 'Journal Article',
        'title': 'Widespread decoupling of spindles and slow waves in temporal lobe epilepsy',
        'authors': 'K. Schiller, N. von Ellenrieder, D. Mansilla, C. Abdallah, K. Jaber, A. Garcia-Asensi, J. Thomas, E. Minato, J. Gotman, B. Frauscher',
        'status': 'Published',
        'venue': 'Epilepsia',
        'notes': '2025',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2025 Epilepsia spindles slow waves temporal lobe epilepsy'
    },
    {
        'id': 'journal-2024-sleep-effects-ictal-interictal-networks',
        'category': 'Other Journal Publications',
        'year': 2024,
        'type': 'Journal Article',
        'title': 'The Differing Effects of Sleep on Ictal and Interictal Network Dynamics in Drug-Resistant Epilepsy',
        'authors': 'S. Hannan, J. Thomas, K. Jaber, C. El Kosseifi, A. Ho, C. Abdallah, T. Avigdor, J. Gotman, B. Frauscher',
        'status': 'Published',
        'venue': 'Annals of Neurology',
        'notes': 'vol. 95, no. 1, pp. 42–56, 2024',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2024 Annals of Neurology sleep ictal interictal network dynamics'
    },
    {
        'id': 'journal-2024-pulsatile-corticoid-therapy',
        'category': 'Other Journal Publications',
        'year': 2024,
        'type': 'Journal Article',
        'title': 'Pulsatile Corticoid Therapy Reduces Interictal Epileptic Activity Burden in Children with Genetic Drug-Resistant Epilepsy',
        'authors': 'K. Schiller, J. Thomas, T. Avigdor, D. Mansilla, A. Kortas, G. Unterholzner, M. Rauchenzauner',
        'status': 'Published',
        'venue': 'Epilepsia Open',
        'notes': '2024',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2024 Epilepsia Open corticoid therapy interictal epileptic activity'
    },
    {
        'id': 'journal-2024-spatial-perturbation-framework',
        'category': 'Other Journal Publications',
        'year': 2024,
        'type': 'Journal Article',
        'title': 'A Spatial Perturbation Framework to Validate Implantation of the Epileptogenic Zone',
        'authors': 'K. Jaber, T. Avigdor, J. Thomas, D. Mansilla, C. Abdallah, A. Kortas, G. Unterholzner, R. Pana, M. Rauchenzauner, B. Frauscher',
        'status': 'Published',
        'venue': 'Nature Communications',
        'notes': 'vol. 15, no. 1, p. 5253, 2024',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2024 Nature Communications spatial perturbation epileptogenic zone'
    },
    {
        'id': 'journal-2024-spike-ripples-localize-epileptogenic-zone',
        'category': 'Other Journal Publications',
        'year': 2024,
        'type': 'Journal Article',
        'title': 'Spike Ripples Localize the Epileptogenic Zone Best: An International Intracranial Study',
        'authors': 'W. Shi, D. Shaw, K. G. Walsh, X. Han, U. T. Eden, R. M. Richardson, S. V. Gliske, J. Jacobs, B. H. Brinkmann, G. A. Worrell, W. C. Stacey, B. Frauscher, J. Thomas, M. A. Kramer, C. J. Chu',
        'status': 'Published',
        'venue': 'Brain',
        'notes': 'awae037, 2024',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2024 Brain spike ripples epileptogenic zone intracranial study'
    },
    {
        'id': 'journal-2024-automated-seizure-type-classification',
        'category': 'Other Journal Publications',
        'year': 2024,
        'type': 'Journal Article',
        'title': 'Automated multi-class seizure-type classification system using EEG signals and machine learning algorithms',
        'authors': 'S. Abirami, M. Kathiravan, R. Yuvaraj, R. N. Menon, J. Thomas, P. A. Karthick, A. A. Prince, J. F. A. Ronickom',
        'status': 'Published',
        'venue': 'IEEE Access',
        'notes': 'vol. 12, pp. 136524–136541, 2024',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2024 IEEE Access automated seizure type classification EEG'
    },
    {
        'id': 'journal-2024-oscillatory-nonoscillatory-sleep-biomarkers',
        'category': 'Other Journal Publications',
        'year': 2024,
        'type': 'Journal Article',
        'title': 'Oscillatory and Nonoscillatory Sleep Electroencephalographic Biomarkers of the Epileptic Network',
        'authors': 'V. Latreille, J. Corbin-Lapointe, L. Peter-Derex, J. Thomas, J.-M. Lina, B. Frauscher',
        'status': 'In Press',
        'venue': 'Epilepsia',
        'notes': 'in press, 2024',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2024 in press Epilepsia sleep biomarkers epileptic network'
    },
    {
        'id': 'journal-2023-rem-sleep-ictal-interictal-dynamics',
        'category': 'Other Journal Publications',
        'year': 2023,
        'type': 'Journal Article',
        'title': 'Rapid eye movement sleep affects interictal epileptic activity differently in mesiotemporal and neocortical areas',
        'authors': 'A. Ho, S. Hannan, J. Thomas, T. Avigdor, C. Abdallah, F. Dubeau, J. Gotman, B. Frauscher',
        'status': 'Published',
        'venue': 'Epilepsia',
        'notes': 'vol. 64, no. 11, pp. 3036–3048, 2023',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2023 REM sleep interictal epileptic activity mesiotemporal neocortical'
    },
    {
        'id': 'journal-2023-scalp-hippocampal-sleep-memory',
        'category': 'Other Journal Publications',
        'year': 2023,
        'type': 'Journal Article',
        'title': 'Scalp and hippocampal sleep correlates of memory function in drug-resistant temporal lobe epilepsy',
        'authors': 'V. Latreille, T. Avigdor, J. Thomas, J. Crane, V. Sziklas, M. Jones-Gotman, B. Frauscher',
        'status': 'Published',
        'venue': 'Sleep',
        'notes': 'zsad228, 2023',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2023 Sleep scalp hippocampal sleep correlates memory function'
    },
    {
        'id': 'journal-2023-feature-extraction-emotion-recognition',
        'category': 'Other Journal Publications',
        'year': 2023,
        'type': 'Journal Article',
        'title': 'Comprehensive analysis of feature extraction methods for emotion recognition from multichannel EEG recordings',
        'authors': 'R. Yuvaraj, P. Thangavel, J. Thomas, J. Fogarty, F. Ali',
        'status': 'Published',
        'venue': 'Sensors',
        'notes': 'vol. 23, no. 2, p. 915, 2023',
        'url': 'https://doi.org/10.3390/s23020915',
        'doi': '10.3390/s23020915',
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2023 Sensors emotion recognition EEG feature extraction'
    },
    {
        'id': 'journal-2023-cnn-transformer-belief-matching-seizure-detection',
        'category': 'Other Journal Publications',
        'year': 2023,
        'type': 'Journal Article',
        'title': 'Six-center assessment of CNN-transformer with belief matching loss for patient-independent seizure detection in EEG',
        'authors': 'W. Y. Peh, P. Thangavel, Y. Yao, J. Thomas, Y.-L. Tan, J. Dauwels',
        'status': 'Published',
        'venue': 'International Journal of Neural Systems',
        'notes': 'vol. 33, no. 03, p. 2350012, 2023',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2023 seizure detection CNN transformer belief matching EEG'
    },
    {
        'id': 'journal-2023-pre-ictal-interval-time-period',
        'category': 'Other Journal Publications',
        'year': 2023,
        'type': 'Journal Article',
        'title': 'Optimization of Pre-Ictal Interval Time Period for Epileptic Seizure Prediction Using Temporal and Frequency Features',
        'authors': 'A. A. Shaik Gadda, D. Vedantham, J. Thomas, Y. Rajamanickam, R. N. Menon, J. F. A. Ronickom',
        'status': 'Published',
        'venue': 'Studies in Health Technology and Informatics',
        'notes': 'vol. 302, pp. 232–236, 2023',
        'url': 'https://europepmc.org/article/med/37203653',
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2023 seizure prediction pre-ictal interval temporal frequency EEG'
    },
    {
        'id': 'journal-2023-targeted-density-electrode-placement',
        'category': 'Other Journal Publications',
        'year': 2023,
        'type': 'Journal Article',
        'title': 'Targeted density electrode placement achieves high concordance with traditional high-density EEG for electrical source imaging in epilepsy',
        'authors': 'A. Horrillo-Maysonnial, T. Avigdor, C. Abdallah, D. Mansilla, J. Thomas, N. von Ellenrieder, J. Royer, B. Bernhardt, C. Grova, J. Gotman, B. Frauscher',
        'status': 'Published',
        'venue': 'Clinical Neurophysiology',
        'notes': '2023',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2023 Clinical Neurophysiology targeted density electrode placement'
    },
    {
        'id': 'journal-2021-multi-center-validation-slowing-classification',
        'category': 'Other Journal Publications',
        'year': 2021,
        'type': 'Journal Article',
        'title': 'Multi-center validation study of automated classification of pathological slowing in adult scalp electroencephalograms via frequency features',
        'authors': 'W. Y. Peh, J. Thomas, E. Bagheri, R. Chaudhari, S. Karia, R. Rathakrishnan, V. Saini, N. Shah, R. Srivastava, Y. L. Tan, J. Dauwels',
        'status': 'Published',
        'venue': 'International Journal of Neural Systems',
        'notes': 'vol. 31, no. 06, p. 2150016, 2021',
        'url': 'https://doi.org/10.1142/S0129065721500167',
        'doi': '10.1142/S0129065721500167',
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2021 pathological slowing adult scalp EEG frequency features'
    },
    {
        'id': 'journal-2021-time-frequency-decomposition-deep-learning',
        'category': 'Other Journal Publications',
        'year': 2021,
        'type': 'Journal Article',
        'title': 'Time–frequency decomposition of scalp electroencephalograms improves deep learning-based epilepsy diagnosis',
        'authors': 'P. Thangavel, J. Thomas, W. Y. Peh, J. Jing, R. Yuvaraj, S. S. Cash, R. Chaudhari, S. Karia, R. Rathakrishnan, V. Saini, N. Shah, R. Srivastava, Y. L. Tan, B. Westover, J. Dauwels',
        'status': 'Published',
        'venue': 'International Journal of Neural Systems',
        'notes': 'vol. 31, no. 08, p. 2150032, 2021',
        'url': 'https://doi.org/10.1142/S0129065721500325',
        'doi': '10.1142/S0129065721500325',
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2021 time-frequency decomposition scalp EEG deep learning diagnosis'
    },
    {
        'id': 'journal-2021-autism-fmri-functional-brain-connectivity',
        'category': 'Other Journal Publications',
        'year': 2021,
        'type': 'Journal Article',
        'title': 'Diagnostic classification of autism using resting-state fMRI data improves with full correlation functional brain connectivity compared to partial correlation',
        'authors': 'J. F. A. Ronickom, J. Thomas, P. Thangavel, V. Koneru, G. Langs, J. Dauwels',
        'status': 'Published',
        'venue': 'NeuroImage: Clinical',
        'notes': 'vol. 32, p. 102831, 2021',
        'url': 'https://doi.org/10.1016/j.nicl.2021.102831',
        'doi': '10.1016/j.nicl.2021.102831',
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'journal 2021 NeuroImage Clinical autism classification resting-state fMRI'
    },
    {
        'id': 'conference-2023-eeg-biometric-authentication-feasibility-study',
        'category': 'Conference Papers',
        'year': 2023,
        'type': 'Conference Paper',
        'title': 'A feasibility study on using EEG for biometric trait authentication system',
        'authors': 'D. Jeswani, P. Kumar Govarthan, A. Selvaraj, J. Thomas, J. F. Agastinose Ronickom',
        'status': 'Published',
        'venue': 'Current Directions in Biomedical Engineering',
        'notes': 'De Gruyter, vol. 9, 2023, pp. 690–693',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'conference 2023 EEG biometric authentication Current Directions in Biomedical Engineering'
    },
    {
        'id': 'conference-2023-multiclass-seizure-type-classification',
        'category': 'Conference Papers',
        'year': 2023,
        'type': 'Conference Paper',
        'title': 'Multi-class seizure type classification using features extracted from the EEG',
        'authors': 'A. Selvaraj, S. Pj, J. Thomas, Y. Rajamanickam, R. N. Menon, J. F. Agastinose Ronickom',
        'status': 'Published',
        'venue': 'Healthcare Transformation with Informatics and Artificial Intelligence',
        'notes': 'IOS Press, 2023, pp. 68–71',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'conference 2023 seizure type classification EEG Healthcare Transformation IOS Press'
    },
    {
        'id': 'conference-2020-deep-learning-interictal-spike-detection',
        'category': 'Conference Papers',
        'year': 2020,
        'type': 'Conference Paper',
        'title': 'Deep learning for interictal epileptiform spike detection from scalp EEG frequency sub bands',
        'authors': 'T. Prasanth, J. Thomas, R. Yuvaraj, J. Jing, S. S. Cash, R. Chaudhari, Y. L. Tan, R. Rathakrishnan, R. Srivastava, V. Saini, B. M. Westover, J. Dauwels',
        'status': 'Published',
        'venue': 'IEEE EMBC',
        'notes': '2020, pp. 3703–3706',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'conference 2020 IEEE EMBC interictal epileptiform spike detection deep learning'
    },
    {
        'id': 'conference-2018-eeg-classification-cnn-interictal-event-detection',
        'category': 'Conference Papers',
        'year': 2018,
        'type': 'Conference Paper',
        'title': 'EEG classification via convolutional neural network-based interictal epileptiform event detection',
        'authors': 'J. Thomas, L. Comoretto, J. Jin, J. Dauwels, S. S. Cash, M. B. Westover',
        'status': 'Published',
        'venue': 'IEEE EMBC',
        'notes': '2018, pp. 3148–3151',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'conference 2018 EEG classification CNN interictal event detection'
    },
    {
        'id': 'conference-2018-deep-learning-seizure-detection',
        'category': 'Conference Papers',
        'year': 2018,
        'type': 'Conference Paper',
        'title': 'A deep learning scheme for automatic seizure detection from long-term scalp EEG',
        'authors': 'R. Yuvaraj, J. Thomas, T. Kluge, J. Dauwels',
        'status': 'Published',
        'venue': 'Asilomar Conference on Signals, Systems, and Computers',
        'notes': 'IEEE, 2018, pp. 368–372',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'conference 2018 seizure detection long-term scalp EEG deep learning'
    },
    {
        'id': 'conference-2017-affinity-propagation-spike-detection',
        'category': 'Conference Papers',
        'year': 2017,
        'type': 'Conference Paper',
        'title': 'Automated epileptiform spike detection via affinity propagation-based template matching',
        'authors': 'J. Thomas, J. Jin, J. Dauwels, S. S. Cash, M. B. Westover',
        'status': 'Published',
        'venue': 'IEEE EMBC',
        'notes': '2017, pp. 3057–3060',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'conference 2017 epileptiform spike detection affinity propagation template matching'
    },
    {
        'id': 'conference-2017-deep-learning-bci-classification',
        'category': 'Conference Papers',
        'year': 2017,
        'type': 'Conference Paper',
        'title': 'Deep learning-based classification for brain-computer interfaces',
        'authors': 'J. Thomas, T. Maszczyk, N. Sinha, T. Kluge, J. Dauwels',
        'status': 'Published',
        'venue': 'IEEE SMC',
        'notes': '2017, pp. 234–239',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'conference 2017 brain-computer interfaces deep learning classification'
    },
    {
        'id': 'conference-2016-clustering-interictal-spikes',
        'category': 'Conference Papers',
        'year': 2016,
        'type': 'Conference Paper',
        'title': 'Clustering of interictal spikes by dynamic time warping and affinity propagation',
        'authors': 'J. Thomas, J. Jin, J. Dauwels, S. S. Cash, M. B. Westover',
        'status': 'Published',
        'venue': 'IEEE ICASSP',
        'notes': '2016, pp. 749–753',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'conference 2016 interictal spikes clustering dynamic time warping affinity propagation'
    },
    {
        'id': 'bookchapter-2022-neonatal-seizure-detection-ee',
        'category': 'Book Chapters',
        'year': 2022,
        'type': 'Book Chapter',
        'title': 'A Comparative Study on EEG Features for Neonatal Seizure Detection',
        'authors': 'S. Abirami, J. Thomas, R. Yuvaraj, J. F. A. Ronickom',
        'status': 'Published',
        'venue': 'Springer',
        'notes': '2022, pp. 43–64',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'book chapter 2022 EEG neonatal seizure detection'
    },
    {
        'id': 'bookchapter-2022-epilepsy-diagnosis-monitoring',
        'category': 'Book Chapters',
        'year': 2022,
        'type': 'Book Chapter',
        'title': 'Computational Approaches for Diagnosis and Monitoring of Epilepsy from Scalp EEG',
        'authors': 'R. Yuvaraj, J. Thomas, E. Bagheri, J. Dauwels, R. Rathakrishnan, Y. L. Tan',
        'status': 'Published',
        'venue': 'Springer',
        'notes': '2022, pp. 1–31',
        'url': None,
        'doi': None,
        'abstract': 'Abstract unavailable. Add a short summary here.',
        'keywords': 'book chapter 2022 Computational Approaches Diagnosis Monitoring Epilepsy Scalp EEG'
    }
]

index = {'entries': []}
for entry in entries:
    filename = f"{entry['id']}.json"
    filepath = ENTRIES_DIR / filename
    with filepath.open('w', encoding='utf-8') as f:
        json.dump(entry, f, indent=2, ensure_ascii=False)
    index['entries'].append({'id': entry['id'], 'file': f'entries/{filename}', 'year': entry['year'], 'category': entry['category']})

with (PUB_DIR / 'index.json').open('w', encoding='utf-8') as f:
    json.dump(index, f, indent=2, ensure_ascii=False)

print(f'Created {len(entries)} publication entry files and publications/index.json')
